/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ListActionButtons: typeof import('./src/components/ListActionButtons.vue')['default']
    ListWrapper: typeof import('./src/components/ListWrapper.vue')['default']
    NewItemField: typeof import('./src/components/NewItemField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveListDialog: typeof import('./src/components/SaveListDialog.vue')['default']
    ShoppingList: typeof import('./src/components/ShoppingList.vue')['default']
    ShoppingListTitle: typeof import('./src/components/ShoppingListTitle.vue')['default']
  }
}
